const fs = require('fs');
const path = require('path');

function walk(dir) {
  let results = [];
  const list = fs.readdirSync(dir);
  list.forEach(file => {
    file = path.join(dir, file);
    const stat = fs.statSync(file);
    if (stat && stat.isDirectory()) { 
      results = results.concat(walk(file));
    } else { 
      if (file.endsWith('.spec.ts')) {
        results.push(file);
      }
    }
  });
  return results;
}

const specs = walk(path.join(__dirname, 'src'));

specs.forEach(file => {
  let content = fs.readFileSync(file, 'utf8');
  let changed = false;

  // Replace async from testing import
  if (content.includes('async,') || content.includes(', async') || content.includes('{ async }')) {
    content = content.replace(/import\s+{(.*)async(.*)}\s+from\s+['"]@angular\/core\/testing['"]/g, 
      (match, p1, p2) => {
        return `import {${p1}waitForAsync${p2}} from '@angular/core/testing'`;
      }
    );
    // Replace the usage
    content = content.replace(/async\(\(\)\s*=>/g, 'waitForAsync(() =>');
    changed = true;
  }

  // Fix my script error: BrowserAnimationsModule -> NoopAnimationsModule
  if (content.includes('BrowserAnimationsModule')) {
    content = content.replace(/BrowserAnimationsModule/g, 'NoopAnimationsModule');
    content = content.replace(/@angular\/platform-browser\/animations/g, '@angular/platform-browser/animations');
    changed = true;
  }

  // Fix missing imports from empty autogenerated files
  if (file.includes('detalle-documento.spec.ts')) {
     content = content.replace("import { DetalleDocumento } from './detalle-documento';", "");
     changed = true;
  }
  if (file.includes('documento.service.spec.ts')) {
     content = content.replace("import { Documento } from './documento';", "");
     changed = true;
  }
  if (file.includes('observacion-liquidacion.spec.ts')) {
     content = content.replace("import { ObservacionLiquidacion } from './observacion-liquidacion';", "import { ObservacionLiquidacionService } from './observacion-liquidacion';");
     changed = true;
  }
  if (file.includes('exchange.service.spec.ts')) {
     content = content.replace("import { Exchange } from './exchange.service';", "");
     changed = true;
  }

  if (changed) {
    fs.writeFileSync(file, content, 'utf8');
    console.log('Fixed', file);
  }
});
