[build]
  # 1. Base directory: Donde está el package.json de Angular.
  base    = "everywhere-frontend"

  # 2. Build command: El comando que genera la aplicación de producción.
  command = "npm run build"

  # 3. Publish directory: La carpeta que Angular genera (outputPath).
  publish = "dist/everywhere-frontend"

# 4. Regla de redireccionamiento (Corrige el 404 de Angular)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
